### PR TITLE
card component added

### PR DESCRIPTION
**Pull request by qaidjoharj53**
Tasks I have completed:

- I have improved the alignment of images on home page.
- I have added card component.
- I have made the webapp responsive for all screen sizes.
- I have added the functionality to close the image card whenever clicked on either `close` button or anywhere on the screen.

Now when you click on any image it would preview like this 👇
image

image

### CODE REVIEW

**Comment by qaidjoharj53** [comment]
@mohitahlawat2001 
Kindly assign, review and merge this PR under hacktoberfest-accepted label.
So that I can work upon improving UI issue #5 and PR separately.

**Review by mohitahlawat2001 — COMMENTED** [review]
resolve conflict!

**Comment by qaidjoharj53** [comment]
> resolve conflict!

Yeah I am working upon it!
Fill finish it under 15 mins.

**Comment by qaidjoharj53** [comment]
@mohitahlawat2001 
The conflicts are being resolved!

**Comment by qaidjoharj53** [comment]
@mohitahlawat2001 
What happen sir?
Please merge this PR so that I can PR for my next issues too!

Please add _Hacktoberfest-accepted_ label as mentioned in Hacktoberfest T&C

**Pull request merged**
