### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by qaidjoharj53**
I have added 
table contents
`npm install`
And license.

If you want to add badges, let me know, I'll add that too!

### CODE REVIEW

**Comment by qaidjoharj53** [comment]
Please label this PR as hactoberfest-accepted

**Comment by qaidjoharj53** [comment]
I want to PR for different issues also so it would be very helpful if you merge this PR @mohitahlawat2001

**Comment by qaidjoharj53** [comment]
I will add the new card component functionality code in a new PR as no. of PRs are counted by hactoberfest.
I request you to merge this PR fast

**Review by mohitahlawat2001 — COMMENTED** [review]
make more change in readme remove all unnecessary content

**Comment by qaidjoharj53** [comment]
@mohitahlawat2001 Can you please be more specific...

**Pull request merged**
